[project]
name = "openai-sdk-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "openai-agents>=0.6.8",
]

[dependency-groups]
dev = [
    "ipykernel>=6.31.0",
]
